entryPoints:
  http-443:
    http:
      middlewares:
        - trafic-forward-auth-middleware@file

  http-80:
    http:
      middlewares:
        - trafic-forward-auth-middleware@file

  http-2052:
    http:
      middlewares:
        - trafic-forward-auth-middleware@file

  http-2053:
    http:
      middlewares:
        - trafic-forward-auth-middleware@file
