#ddev-generated
log:
  format: json
accesslog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop
      names:
        RequestHost: keep

entryPoints:
  traefik:
    http:
      middlewares:
        - ddev-auth@file

  http-443:
    http:
      middlewares:
        - ddev-auth@file

  http-80:
    http:
      middlewares:
        - ddev-auth@file

  http-2052:
    http:
      middlewares:
        - ddev-auth@file

  http-2053:
    http:
      middlewares:
        - ddev-auth@file
