services:
  middleware:
    build:
      context: .
      network: host
    container_name: trafic-middleware
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - REDIS_HOST=redis
    networks:
      - trafic-network
      - ddev_default
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - .:/app
    restart: always
    working_dir: /app

  queue:
    image: webdevops/php:8.3
    container_name: trafic-queue
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - REDIS_HOST=redis
    networks:
      - trafic-network
    volumes:
      - .:/app
    restart: always
    working_dir: /app
    command: ["php", "/app/bin/console", "messenger:consume", "--all", "-vvv"]

  redis:
    image: redis:7.4.2
    container_name: trafic-redis
    networks:
      - trafic-network
    ports:
      - "6379:6379"
    volumes:
      - trafic-redis-data:/data

volumes:
  trafic-redis-data: {}

networks:
  trafic-network:
    driver: bridge
  ddev_default:
    external: true
    name: ddev_default
