services:
  middleware:
    build: .
    container_name: ddev-server-traefik-middleware
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - REDIS_HOST=redis
    networks:
      - ddev-server-network
      - ddev_default
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - .:/app
    restart: always
    working_dir: /app

  queue:
    image: webdevops/php:8.3
    container_name: ddev-server-queue
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - REDIS_HOST=redis
    networks:
      - ddev-server-network
    volumes:
      - .:/app
    restart: always
    working_dir: /app
    command: ["php", "/app/bin/console", "messenger:consume", "async"]

  redis:
    image: redis:7.4.2
    container_name: ddev-server-redis
    networks:
      - ddev-server-network
    ports:
      - "6379:6379"
    volumes:
      - ddev-server-redis-data:/data

volumes:
  ddev-server-redis-data: {}

networks:
  ddev-server-network:
    driver: bridge
  ddev_default:
    external: true
    name: ddev_default
